# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/tidsbokning

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - gem-v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - gem-v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: gem-v1-dependencies-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
            - yarn-v1-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-v1-cache-{{ .Branch }}
            - yarn-v1-cache

      - run: yarn install

      - save_cache:
          key: yarn-v1-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: bundle exec rails test
